spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# swagger-ui
springdoc:
  paths-to-match: /api/v1/**
  swagger-ui:
    use-root-path: true

server:
  port: 80